sml retouche

diff --git a/bin/scitopdf b/bin/scitopdf
--- a/bin/scitopdf
+++ b/bin/scitopdf
@@ -10,11 +10,14 @@ destination=$HOME/downloads/scitopdf
 [ -d $destination ] || mkdir -p "$destination" &> /dev/null || \
 	echo -e "$(tput setf 4)Can't create downloads directory to $destination.\nPlease be sure you have permissions.\nPapers will not be stored.$(tput sgr0)"
 
-# Check internet connection
+# Quickly check internet connection
 [[ -z $(ping -q -w1 -c1 1.1.1.1) ]] && echo "No internet connection." && exit 1
 
 # Check $READER variable (pdf reader)
-[[ -v READER ]] || echo -e "No PDF reader.\nTry setting a \$READER variable, or install zathura." && READER=zathura
+[[ -v READER ]] || \
+	if ! ( READER=zathura && command -v zathura &>/dev/null ); then
+		echo -e "No PDF reader.\nTry setting a \$READER variable, or install zathura."
+	fi
 
 # Open PDF automatically after download
 automatically_open="yes"
@@ -63,7 +66,6 @@ locate_website() {
 		exit 1;
 	else
 		echo $site > "/tmp/sci_address"
-		echo Sci-hub is here : $site
 	fi
 }
 	#__________________________#
@@ -80,7 +82,7 @@ if ! [[ $(echo $doi) = "" ]]; then
 else
 	echo $(tput setaf 1)"DOI not found."$(tput sgr0)
 	notify-send "scitopdf" "DOI not found."
-	exit 1;
+	[[ ! -v listing ]] && exit 1;
 fi
 }
 	#________________#
@@ -92,6 +94,7 @@ if ! [[ $(echo "$concatenate") = "" ]]; then
 	user_search=$(echo $concatenate | sed "s/'/\ /" | sed 's/\ /+/g' | iconv -f utf8 -t ascii//TRANSLIT)
 	#notify-send "scitopdf" "Looking for '$(echo $user_search | sed 's/+/\ /g')'"
 	# if sci-hub's website in user search, download this specific link:
+	[[ -v listing ]] && echo -e "\n$(tput bold)[Reference $ref_index]$(tput sgr0) $(tput setf 1)$line$(tput sgr0)"
 	if [[ $(echo $user_search | grep -o "$site") = "$site" ]]; then
 		download_link=$(curl -s "$user_search" | grep -io "http.*\.pdf" | head -n 1)
 		if [[ $download_link = "" ]]; then
@@ -128,7 +131,7 @@ if ! [[ $(echo "$concatenate") = "" ]]; then
 	if [[ $download_link = "" || $download_link = "https:" ]]; then
 		echo $(tput setaf 1)"Empty download link."$(tput sgr0)
 		#notify-send "Empty download link."
-		exit
+		return
 	fi
 	#echo "Download link : $download_link"
 	filename=$(echo $download_link | sed 's:.*/::')
@@ -140,7 +143,7 @@ if ! [[ $(echo "$concatenate") = "" ]]; then
 		else
 			#notify-send "Paper not found."
 			echo $(tput setaf 3)"Paper not found.\\nPlease check if your country is not blocking access to Sci-Hub. Use a VPN if possible."$(tput sgr0)
-			exit 1;
+			[[ ! -v listing ]] && exit 1;
 		fi
 	else
 		#echo "Downloading '$filename' to '$destination'."
@@ -150,7 +153,7 @@ if ! [[ $(echo "$concatenate") = "" ]]; then
 		#notify-send "Paper downloaded!"
 		echo $(tput setaf 2)"Done!"$(tput sgr0)
 		if [ $(echo $automatically_open) = "yes" ]; then
-			setsid $READER "$destination/$filename"
+			setsid "$READER" "$destination/$filename"
 		fi
 #		exit 1;
 	fi
@@ -168,9 +171,11 @@ fi
 # Arguments' evaluation : if "-l" or "--list" as first argument, scitopdf looks inside a file (2nd argument) which should contain several references
 if [[ $(echo $1) = "-l" || $(echo $1) = "--list" ]]; then
 	automatically_open="no"
+	listing=true
 	locate_website
-	while read line; do concatenate=$(echo $line);  paper_search "$line"; done < $2
-	exit 1
+	ref_index=0
+	while read line; do concatenate=$(echo $line); ref_index=$(( $ref_index + 1 )); paper_search "$line"; done < $2
+	echo ">> End of file \"$2\"" && exit 1
 else
 	# If no option specified, then every word following scitopdf is considered as the title
 	args=("$@")
@@ -190,14 +195,14 @@ if [[ $(echo $concatenate | grep -io http) == "http" ]]; then
 	filename=$(echo $download_link | sed 's:.*/::')
 	cd $destination
 	if [[ $(echo $filename) == "" ]]; then
-		echo "Article not found. Please check if your country is not blocking access to Sci-Hub. Use a VPN if possible."
-		exit;
+		echo "Paper not found. Please check if your country is not blocking access to Sci-Hub. Use a VPN if possible."
+		[[ ! -v listing ]] && exit;
 	else
 		echo $(tput bold)"Downloading ..."$(tput sgr0)
 		curl "$download_link" --output "$filename" --progress-bar
 		echo $(tput setaf 2)"Done!"$(tput sgr0)
 		if [ $(echo $automatically_open) = "yes" ]; then
-			setsid $READER "$destination/$filename"
+			setsid "$READER" "$destination/$filename"
 		fi
 	fi
 else
