elaging

diff --git a/bin/scitopdf b/bin/scitopdf
--- a/bin/scitopdf
+++ b/bin/scitopdf
@@ -2,52 +2,41 @@
 #
 # Download articles from Sci-Hub
 
-#########################################
 # Folder in which article is downloaded #
-#########################################
 destination=$HOME/downloads/scihub
 
 if ! [ -d $destination ]; then
 	mkdir $destination
 fi
 
-############################
 # Check internet connexion #
-############################
 statut_connexion=$(echo $(ping -q -w1 -c1 google.com &>/dev/null && echo online || echo offline))
 if [ $(echo $statut_connexion) = "offline" ]; then
 	echo No internet connexion.
 	exit 1
 fi
 
-#########################################
 # Open PDF automatically after download #
-#########################################
 automatically_open="yes"
 
 ##############
 # Functions  #
 ##############
-
-	########################
 	# Find Sci-Hub website #
-	########################
 localiser_site() {
 echo "Looking for website..."
 site=$(curl -s -LH "" "https://sci-hub.now.sh/" | grep -i https://sci-hub... | grep -i biglink | tail -n 1 | grep -io https://sci-hub... | tail -n 1)
 echo "Checking connexion to : $site"
 if [[ $(echo $(curl -v $site 2>&1) | grep -io "Could not resolve" | tail -n 1) = $(echo "Could not resolve") ]]; then
 	echo "Sci-Hub's website not found. Check https://sci-hub.now.sh/"
-	exit 1
+	exit 1;
 else
 	echo $site > /tmp/sci_address
 	echo Sci-hub is here : $site
 fi
 }
 
-	############################
 	# Look for DOI on Crossref #
-	############################
 recherche_doi() {
 echo "Paper found on Crossref. Looking for DOI."
 doi=$(echo $(curl -A "Mozilla/5.0 (x11; ubuntu; linux x86_64; rv:59.0) gecko/20100101 firefox/59.0" -s "https://search.crossref.org/?q=$recherche&from_ui=yes" | grep -io "https://doi.*" | grep -io "doi.*" | sed 's/http:\/\///' | grep -io "/.*" | sed 's/\///' | head -n 2 | tail -n 1))
@@ -65,9 +54,7 @@ else
 fi
 }
 
-	####################
 	# Look for article #
-	####################
 recherche_article() {
 if ! [[ $(echo "$concatener") = "" ]]; then
 	recherche=$(echo $concatener | sed "s/'/\ /g" | sed 's/\ /+/g' | iconv -f utf8 -t ascii//TRANSLIT)
@@ -83,8 +70,8 @@ if ! [[ $(echo "$concatener") = "" ]]; then
 			notify-send "Paper not available on Sci-Hub."
 			echo "Paper not available on Sci-Hub."
 		else
-			notify-send "Impossible to get the paper."
-			echo "Paper not found. Please check if your country is not blocking access to Sci-Hub. Use a VPN if possible."
+			notify-send "Paper not found."
+			echo "Paper not found.\\nPlease check if your country is not blocking access to Sci-Hub. Use a VPN if possible."
 			exit 1;
 		fi
 	else
@@ -105,34 +92,28 @@ fi
 }
 
 
-###########################################
 # Option to download articles from a list #
-###########################################
 # Arguments evaluation : if "-l" or "--list" as first argument, then scitopdf will look inside a .txt file (2nd argument) which would contain several references
 if [[ $(echo $1) = "-l" || $(echo $1) = "--list" ]]; then
 	automatically_open="no"
 	localiser_site
 	while read line; do concatener=$(echo $line);  recherche_article "$line"; done < $2
 	exit 1
-else
-# If no option specified, then every word following scitopdf is considered as the title (note that it can contain name of author, year, etc. with no problem)
-	# regrouper tous les arguments
-	# regrouper les arguments dans une liste
-	args=("$@")
-	# nombre d'arguments
-	ELEMENTS=${#args[@]}
-	# echo chaque element dans une liste
-	# for loop
-	for (( i=0;i<$ELEMENTS;i++)); do
-	    #echo -n ${args[${i}]}"\ "
-	    concatener=$(echo $concatener" ")$(echo -n ${args[${i}]}"\ ")
-	done
 fi
-
 
 ################
 # Start script #
 ################
+# If no option specified, then every word following scitopdf is considered as the title
+# regrouper les arguments dans une liste
+args=("$@")
+# nombre d'arguments
+ELEMENTS=${#args[@]}
+# echo chaque element dans une liste
+for (( i=0;i<$ELEMENTS;i++)); do
+    #echo -n ${args[${i}]}"\ "
+    concatener=$(echo $concatener" ")$(echo -n ${args[${i}]}"\ ")
+done
 
 if [[ $(echo $concatener | grep -io http) == "http" ]]; then
 	localiser_site
