sml changes

diff --git a/bin/scitopdf b/bin/scitopdf
--- a/bin/scitopdf
+++ b/bin/scitopdf
@@ -4,18 +4,19 @@
 #░▄▀▀░▄▀▀░█░▀█▀░▄▀▄▒█▀▄░█▀▄▒█▀
 #▒▄██░▀▄▄░█░▒█▒░▀▄▀░█▀▒▒█▄▀░█▀
 
-# Downloads folder
+# Downloads folder [change that to your favorite location]
 destination=$HOME/downloads/scitopdf
 
-[ ! -d $destination ] && mkdir $destination
+[ -d $destination ] || mkdir -p "$destination" &> /dev/null || \
+	echo -e "$(tput setf 4)Can't create downloads directory to $destination.\nPlease be sure you have permissions.\nPapers will not be stored.$(tput sgr0)"
 
-# Check internet connexion #
+# Check internet connection
 [[ -z $(ping -q -w1 -c1 1.1.1.1) ]] && echo "No internet connection." && exit 1
 
 # Check $READER variable (pdf reader)
-[[ -v READER ]] || echo -e "No PDF reader.\\nTry setting a \$READER variable, or install zathura." && READER=zathura
+[[ -v READER ]] || echo -e "No PDF reader.\nTry setting a \$READER variable, or install zathura." && READER=zathura
 
-# Open PDF automatically after download #
+# Open PDF automatically after download
 automatically_open="yes"
 
 # Temporary file with different headers avoid(ish)ing blocation
@@ -32,20 +33,21 @@ headers_file=/tmp/scitopdf_headers
 	# Change headers #
 	#----------------#
 change_headers() {
+	cat "$headers_file" | sed '1q' >> "$headers_file"
 	sed -i '1d' "$headers_file"
 	if [[ $(cat "$headers_file") == "" ]]; then
-		echo "Mozilla/5.0 (x11; ubuntu; linux x86_64; rv:59.0) gecko/20100101 firefox/59.0" >> "$headers_file"
-		echo "Mozilla/5.0 (iPad; CPU OS 8_1_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B466 Safari/600.1.4" >> "$headers_file"
-		echo "Mozilla/5.0 (Linux; U; Android 4.0.3; en-us; KFTT Build/IML74K) AppleWebKit/537.36 (KHTML, like Gecko) Silk/3.68 like Chrome/39.0.2171.93 Safari/537.36" >> "$headers_file"
-		echo "Mozilla/5.0 (Windows NT 6.3; Win64; x64; Trident/7.0; rv:11.0) like Gecko" >> "$headers_file"
-		echo "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:40.0) Gecko/20100101 Firefox/40.0" >> "$headers_file"
-		echo "Mozilla/5.0 (X11; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0" >> "$headers_file"
-		echo "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0" >> "$headers_file"
-		echo "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.1) Gecko/2008070208 Firefox/3.0.1" >> "$headers_file"
-		echo "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 BingPreview/1.0b" >> "$headers_file"
-		echo "Mozilla/5.0 (Windows NT 6.3; Win64; x64; Trident/7.0; MAARJS; rv:11.0) like Gecko" >> "$headers_file"
-		echo "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET4.0C; .NET4.0E)" >> "$headers_file"
-		echo "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36" >> "$headers_file"
+		echo "Mozilla/5.0 (x11; ubuntu; linux x86_64; rv:59.0) gecko/20100101 firefox/59.0
+	Mozilla/5.0 (iPad; CPU OS 8_1_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B466 Safari/600.1.4
+	Mozilla/5.0 (Linux; U; Android 4.0.3; en-us; KFTT Build/IML74K) AppleWebKit/537.36 (KHTML, like Gecko) Silk/3.68 like Chrome/39.0.2171.93 Safari/537.36
+	Mozilla/5.0 (Windows NT 6.3; Win64; x64; Trident/7.0; rv:11.0) like Gecko
+	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:40.0) Gecko/20100101 Firefox/40.0
+	Mozilla/5.0 (X11; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0
+	Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0
+	Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.1) Gecko/2008070208 Firefox/3.0.1
+	Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 BingPreview/1.0b
+	Mozilla/5.0 (Windows NT 6.3; Win64; x64; Trident/7.0; MAARJS; rv:11.0) like Gecko
+	Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET4.0C; .NET4.0E)
+	Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36" >> "$headers_file"
 	fi
 	headers=$(echo $(cat "$headers_file" | head -n 1))
 	#echo "Current headers : $headers"
@@ -54,15 +56,15 @@ change_headers() {
 	# Find Sci-Hub #
 	#--------------#
 locate_website() {
-echo $(tput bold)"Looking for website..."$(tput sgr0)
-site=$(curl -s -LH "" "https://sci-hub.now.sh/" | grep -i https://sci-hub... | grep -i biglink | grep -io https://sci-hub... | head -n 1)
-if [[ $(echo $(curl -v $site 2>&1) | grep -io "Could not resolve" | tail -n 1) = $(echo "Could not resolve") ]]; then
-	echo "Sci-Hub not found. \\nCheck https://sci-hub.now.sh\\nFor manual website setting :\\n-insert Sci-Hub's url in the file '/tmp/sci_address'"
-	exit 1;
-else
-	echo $site > "/tmp/sci_address"
-	echo Sci-hub is here : $site
-fi
+	echo $(tput bold)"Looking for website..."$(tput sgr0)
+	site=$(curl -s -LH "" "https://sci-hub.now.sh/" | grep -i https://sci-hub... | grep -i biglink | grep -io https://sci-hub... | head -n 1)
+	if [[ $(echo $(curl -v $site 2>&1) | grep -io "Could not resolve" | tail -n 1) = $(echo "Could not resolve") ]]; then
+		echo -e "Sci-Hub not found. \nCheck https://sci-hub.now.sh\nFor manual website setting, use the -u option"
+		exit 1;
+	else
+		echo $site > "/tmp/sci_address"
+		echo Sci-hub is here : $site
+	fi
 }
 	#__________________________#
 	# Look for DOI on Crossref #
@@ -220,4 +222,4 @@ fi
 exit
 
 # last modif : 2022 apr 01
-# add arguments : -q = no echo ; -w --download-only ; -d --doi ;
+# add arguments : -q = no echo ; -w --download-only ; -d --doi ; -u = url
